name: Elixir CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    name: Build and test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Shutdown Ubuntu MySQL
      run: sudo service mysql stop
    - name: Setup MySQL
      uses: mirromutth/mysql-action@v1.1
      with:
        mysql root_password: sqlsecret
        mysql database: spock_db_test
        mysql user: root
        mysql password: spock_db_test
    - name: Setup Redis
      uses: zhulik/redis-action@1.1.0
    - name: Set up Elixir
      uses: actions/setup-elixir@v1
      with:
        elixir-version: '1.8.2' # Define the elixir version [required]
        otp-version: '22.3' # Define the OTP version [required]
    - name: Restore dependencies cache
      uses: actions/cache@v2
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-
    - name: Install dependencies
      run: mix deps.get
    - name: Setup DB
      env:
        MIX_ENV: test
      run: |
        mix ecto.migrate
    - name: Run tests
      run: |
        mix test
